apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-ohkillsh-win-webapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ohkillsh/killsh-gitops.git
    targetRevision: HEAD
    path: app/web-nginx-traefik
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true